### ISSUE TITLE
Hitting play twice freezes the GUI and Host

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#152]
In Maya, if you press "Publish" and immidiately press the "Publish" button while it is still initialising/collecting, it freezes Pyblish and the host.

**Solution**

Actually, you could have a look at it yourself if you want. It's here.

[pyblish-qml/control.py](https://github.com/pyblish/pyblish-qml/blob/389e2e4dae98ddaf0298e99c6dd6a6646698d4c4/pyblish_qml/control.py#L768)

You'll need to either prevent run from being triggered when Pyblish is already publishing from within the method, or remove the Play button from the GUI when it is publishing so it can't be pressed.

**Comment by mottosso** [comment]
Modified title so it catches my eye (and doesn't sound like an awesome Pyblish feature). :)

**Comment by tokejepsen** [comment]
This seems to have been resolved in the latest version of pyblish-qml, as its not showing the "Publish" when collecting, so the user can't crash Pyblish by clicking it.

**Comment by mottosso** [comment]
Does it still show when you first launch the GUI?

**Comment by tokejepsen** [comment]
> Does it still show when you first launch the GUI?

The "Publish" button does not show during collecting, and launch of the GUI, which is solving this problem by user not being able to click the "Publish" button.

**Comment by tokejepsen** [comment]
I just realized that the "Publish" button shows during collection, when running pyblish-qml/app.py, but it doesn't show in a host like Maya and Nuke.

Its working as I would expect in the hosts, but not in the app.py. Wonder whether it was something to do with ```pyblish-integration```?

**Comment by mottosso** [comment]
It's because when you launch from a host, Pyblish QML is already running and would have already had that first run where the button still shows done.

Ideally it should show anywhere, and it would show if you launch QML when you publish for the first time. So it's a bug.

**Comment by tokejepsen** [comment]
> It's because when you launch from a host, Pyblish QML is already running and would have already had that first run where the button still shows done.

You are right, on the second reset using pyblish-qml/app.py the "Publish" button is hidden.

> So it's a bug.

Separate issue I guess:)

**Comment by tokejepsen** [comment]
Do we want to solve this issue, or just make sure that the "Publish" button doesn't show when Pyblish QML starts?

**Comment by mottosso** [comment]
Hiding it at startup would be a solution I think, and yes, we need to solve it.

**Comment by tokejepsen** [comment]
Just so I get this right, we first need to solve why the "Publish" button doesn't show at all times, then hide/disable it when collecting?

**Comment by mottosso** [comment]
The reason it doesn't show when you publish and validate is due to the "state" that's being emitted to QML. The `self.state` attribute on control.py governs this.

The reason it doesn't happen when you boot up, is because the state isn't officially "publishing" nor "validating". So I think the most secure way of getting similar behaviour is to make the state "publishing" when you boot up. Then it should behave like when you actually do publish.

The reason this is a problem now and not before, is because processing is visible during Collection, which is new.

Getting into the state machine can be a little daunting, but you are welcome to give it a try. It's worth learning about and is vital to GUI programming in general; in my opinion.

Here's an overview of how it works.

- http://doc.qt.io/qt-5/statemachine-api.html

**Comment by BigRoy** [comment]
I'm unable to reproduce this issue with the latest version of pyblish-qml. Are we still able to get the GUI or Host to crash to identify this bug is still there?

**Comment by mottosso** [comment]
Odds are this was a fluke. Closing this until it re-surfaces. Thanks Roy.
